%YAML:1.0
---
Size: [ 960, 600 ]
K_LEFT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 8.4697367805599026e+02, 0.0000000000000000e+00, 4.7321291931751568e+02, 0.0000000000000000e+00,
       8.4942582899505749e+02, 3.1916791301331187e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_LEFT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.1474587124462383e-01, 3.8713147563968070e-01,
       6.1980925913670114e-03, 2.0084258404674486e-03,
       -1.8698240929825376e+00 ]
K_RIGHT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 8.5005265922439492e+02, 0.0000000000000000e+00, 4.6456438104828834e+02, 0.0000000000000000e+00,
       8.5224694812761095e+02, 3.0980459043254575e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_RIGHT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.1007955964812453e-01, 4.6911567111593072e-01,
       5.7310623351495326e-03, -4.6715873626029247e-03,
       -2.2558095214300375e+00 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9999576699604176e-01, -7.9130381868769732e-04,
       2.7999693327935803e-03, 7.8840246603762451e-04,
       9.9999915135915507e-01, 1.0371607981741917e-03, -2.8007876659254362e-03,
       -1.0349489051416027e-03, 9.9999554222467113e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -4.9792984449259677e+01,
       -5.6266522084871685e-02,
       1.0187241587160745e-01 ]
