%YAML:1.0
---
Size: [ 1920, 1200 ]
K_LEFT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.7016014056883264e+03, 0.0000000000000000e+00, 9.2968843721644862e+02, 0.0000000000000000e+00,
       1.7037026044481163e+03, 6.2529186544299523e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_LEFT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.3418009974947712e-01, 3.0484754452767904e-01,
       3.8145716494499262e-03, -1.1987996426111577e-02,
       -1.3741116077428104e+00 ]
K_RIGHT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.6990009489962777e+03, 0.0000000000000000e+00, 1.0323242364613825e+03, 0.0000000000000000e+00,
       1.7009181951613052e+03, 6.1062048526680144e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_RIGHT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.5609810234968150e-01, 2.5784977735097325e-01,
       8.3551512339165399e-04, 1.6933071034464026e-02,
       -1.4746674257749539e+00 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9964311331943778e-01, -2.3111828987650013e-05,
       -2.6714143423757178e-02, 1.9188555978132851e-04,
       9.9998004038472565e-01, 6.3152206687040113e-03, 2.6713464263431942e-02,
       -6.3180929089274853e-03, 9.9962316526231054e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -1.2008246217589934e+02,
       -1.2842431232981685e-01,
       -1.1850572295915511e+00 ]
