%YAML:1.0
---
Size: [ 1920, 1200 ]
K_LEFT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.6769356154935497e+03, 0.0000000000000000e+00, 9.3210037156602527e+02, 0.0000000000000000e+00,
       1.6788125730188954e+03, 6.2582750282425684e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_LEFT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.1500931546499980e-01, 2.6859440522865741e-01,
       3.9161448239020489e-03, -1.1418464550704711e-02,
       -1.0806758444570934e+00 ]
K_RIGHT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.6740158122629518e+03, 0.0000000000000000e+00, 1.0249348310558976e+03, 0.0000000000000000e+00,
       1.6765126767258212e+03, 6.1432446600952619e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_RIGHT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.4001933701054562e-01, 1.6054970978527666e-01,
       1.6229489322749878e-03, 1.2180187105730119e-02,
       -1.1071851692401333e+00 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9977705548864282e-01, -1.9803483148244044e-04,
       -2.1113978797581388e-02, 2.9289608646048684e-04,
       9.9998987781381787e-01, 4.4898197946219012e-03, 2.1112875937250537e-02,
       -4.4950030157011279e-03, 9.9976699356277365e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -1.2026363376989569e+02,
       -4.8727168357480505e-02,
       -2.8995493188897675e-01 ]
