%YAML:1.0
---
Size: [ 1920, 1200 ]
K_LEFT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.7058202270744941e+03, 0.0000000000000000e+00, 9.2756711185729546e+02, 0.0000000000000000e+00,
       1.7085381565203804e+03, 6.2530973778394355e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_LEFT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.2394075413301689e-01, 4.4688577497706045e-01,
       4.0279840735426660e-03, -1.2683473896815112e-02,
       -1.8216952764705125e+00 ]
K_RIGHT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.7030750266844950e+03, 0.0000000000000000e+00, 1.0230698062320268e+03, 0.0000000000000000e+00,
       1.7063666333971896e+03, 6.1372222111639371e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_RIGHT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.4952759728327939e-01, 2.7921825666450201e-01,
       1.7237914226137583e-03, 1.3526909771641992e-02,
       -1.5216064959263740e+00 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9974200603785923e-01, -2.0684566481953280e-04,
       -2.2712960579107933e-02, 3.0813076243469745e-04,
       9.9999002476250809e-01, 4.4559433245633887e-03, 2.2711812319372644e-02,
       -4.4617922799503988e-03, 9.9973209710943067e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -1.1993977641663041e+02,
       -5.8097325077732659e-02,
       -4.0698036484867595e-01 ]
