%YAML:1.0
---
Size: [ 1920, 1200 ]
K_LEFT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.7040426184881919e+03, 0.0000000000000000e+00, 9.3025711598500379e+02, 0.0000000000000000e+00,
       1.7067199391163631e+03, 6.2594985706068769e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_LEFT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.3706374348100462e-01, 2.5652440836376289e-01,
       4.3522180548106887e-03, -1.1228957439064859e-02,
       -1.2809571292303721e+00 ]
K_RIGHT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.7025490672609076e+03, 0.0000000000000000e+00, 1.0285527997470820e+03, 0.0000000000000000e+00,
       1.7051130527452103e+03, 6.1430602624556582e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_RIGHT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.4119402365562342e-01, 3.2311809192697416e-01,
       1.9651033250482528e-03, 1.5406331825496387e-02,
       -1.6480381447039361e+00 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9970807224542757e-01, -2.2319575231411571e-04,
       -2.4160307758533239e-02, 3.3209167845214257e-04,
       9.9998980492387568e-01, 4.5033058330675810e-03, 2.4159056323623144e-02,
       -4.5100146302630324e-03, 9.9969795426698105e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -1.2014839572667591e+02,
       -7.4725484894386143e-02,
       -9.9928515074695201e-01 ]
