%YAML:1.0
---
Size: [ 1920, 1200 ]
K_LEFT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.6691713243186343e+03, 0.0000000000000000e+00, 9.2394407293837241e+02, 0.0000000000000000e+00,
       1.6327192726442975e+03, 6.2830912420214349e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_LEFT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 1.2256602298410137e-01, 9.2786928150439330e-01,
       -1.6656259938155967e-03, -2.4834923781173698e-03,
       -3.2990749970739053e+00 ]
K_RIGHT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.6840178158221827e+03, 0.0000000000000000e+00, 9.1511058003149139e+02, 0.0000000000000000e+00,
       1.6339622376495363e+03, 6.0812864592487529e+02, 0.0000000000000000e+00, 0.0000000000000000e+00, 1.0000000000000000e+00 ]
D_RIGHT: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 1.3237468755006293e-01, 8.1731039035395570e-01,
       -3.6584018948927445e-03, -4.7617660477059058e-03,
       -2.9637806487506637e+00 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9999575732336121e-01, -8.0806349287589887e-04,
       2.7986369304854766e-03, 8.0453622404497551e-04,
       9.9999888098560707e-01, 1.2612489833333735e-03, -2.7996529680293270e-03,
       -1.2589920274732550e-03, 9.9999528843006724e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -4.9964149924280065e+01,
       -1.0903140518037652e-01,
       5.4736831612755810e-01 ]
